import { IReport } from './api.service';

const data: IReport[] = [
  {
    report_id: 1,
    reportName: 'report1',
    report_owner: 'sofiene',
    description: 'Meter',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Active',
  },
  {
    report_id: 2,
    reportName: 'report2',
    report_owner: 'sofiene',
    description: 'Event',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Active',
  },
  {
    report_id: 3,
    reportName: 'report3',
    report_owner: 'sarra',
    description: 'Meter',
    creationDate: '08.03.2022',
    isScheduled: false,
    status: '',
  },
  {
    report_id: 4,
    reportName: 'report4',
    report_owner: 'sarra',
    description: 'Event',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Not Started',
  },
  {
    report_id: 5,
    reportName: 'report5',
    report_owner: 'sofiene',
    description: 'Meter',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Finished',
  },
  {
    report_id: 6,
    reportName: 'report1',
    report_owner: 'sofiene',
    description: 'Meter',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Active',
  },
  {
    report_id: 7,
    reportName: 'report1',
    report_owner: 'sofiene',
    description: 'Meter',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Active',
  },
  {
    report_id: 8,
    reportName: 'report1',
    report_owner: 'sofiene',
    description: 'Meter',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Active',
  },
  {
    report_id: 9,
    reportName: 'report1',
    report_owner: 'sofiene',
    description: 'Meter',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Active',
  },
  {
    report_id: 10,
    reportName: 'report1',
    report_owner: 'sofiene',
    description: 'Meter',
    creationDate: '08.03.2022',
    isScheduled: true,
    status: 'Active',
  }
]

export default data;
